@hostName = http://localhost:6969
@hostNameURL = https://fantasy-app-chi.vercel.app/
@versionURL = api/v1/user
@version = /api/v1/user

@authorization = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2E3YTQ4M2I5M2E0MjkzNmQxOGI3Y2YiLCJ1c2VyTmFtZSI6InByYWRoYW4iLCJpYXQiOjE3MzkwMzk4ODcsImV4cCI6MTczOTA0MzQ4N30.aAlxzWvSKcbN0SNHB4PHTyCwK-tcJFR-LwTlaQ-VGiQ

get {{hostName}}

###

post {{hostName}}{{version}}/register-user
Content-Type: application/json

{
    "name" : "praveen",
    "userName" : "pradhan", 
    "emailId" : "nitesh123@gmail.com", 
    "phone" : "986765131223", 
    "password" : "12345678"
}

###

post {{hostName}}{{version}}/login-user
Content-Type: application/json

{
    "userName" : "pradhan", 
    "password" : "12345678"
}

###

post {{hostName}}{{version}}/deactivate
Content-Type: application/json
Authorization: {{authorization}}

{
    "deactivate" : true
}

###

post {{hostName}}{{version}}/activate
Content-Type: application/json
Authorization: {{authorization}}

{
    "activate" : true
}

###

post {{hostName}}{{version}}/delete-user
Content-Type: application/json
Authorization: {{authorization}}

###

post {{hostName}}{{version}}/logout-user
Content-Type: application/json
Authorization: {{authorization}}